spring:
  datasource:
    url: jdbc:mysql://192.168.31.80:3306/public_health_data
    username: root
    password: public.health.123
  cache:
    type: redis
  data:
    redis:
      host: 192.168.31.80
      database: 1 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: huangdan # Redis服务器连接密码